
all:
	javac -cp .:\* GreenhouseMain.java

manage:
	javac -cp .:\* GreenhouseManagement.java

runManage:
	java -cp .:\* GreenhouseManagement

main:
	javac -cp .:\* GreenhouseMain.java

runMain:
	java -cp .:\* GreenhouseMain	

testing:
	javac -cp .:\* TwoWaySerialComm.java
	
runTest: testing
	java -cp .:\* TwoWaySerialComm

clean:
	rm -rf *.class


